[book]
authors = ["Joeyh021"]
language = "en"
multilingual = false
src = "src"
title = "Computer Systems Engineering Notes"


[preprocessor.katex]
after = ["links"]

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/Joeyh021/notes"
edit-url-template = "https://github.com/Joeyh021/notes/edit/master/{path}"

[output.html.fold]
enable = true
